### ISSUE TITLE
Problem with bigboard if boards have been deleted

### ISSUE THREAD

**Issue by DesertRider** [BlueTeck/kanboard_plugin_bigboard#12]
I encountered a problem with this extension and wanted to write about it... not used to participate so bear with me and indicate me if you need more infos...

I'm using kanboard v1.2.13 with bigboard 1.4.0, on a Red Hat 7 server & MariaDB.

I've created a few test boards to try and demo the bigboard extension to another user. She built her own boards and began using the extension with her boards... so I deleted my 3 demo boards.
When she showed me what she did, I tried to enter into bigboard to use her boards... bigboard could not prompt me to select which boards I wanted to use. No nothing at all.

Later on I figure it out that the problem was that bigboard still was trying to use boards that no longer exist... and hang it there. Maybe a check to verify if the boards selected are still there should be use, or an action be triggered on the deletion of a board... I don't know, just an idea.

To resolve the issue I had to delete entries from the biboard_selected tables that were related to my user.

**Comment by BlueTeck** [comment]
Fixed with version 1.4.1
