### ISSUE TITLE
Bigboard's search overwrites the per-project searches

### ISSUE THREAD

**Issue by johnwoltman** [BlueTeck/kanboard_plugin_bigboard#17]
When I search/filter with Bigboard, the BB search overwrites the per-project searches that are stored in the user's session.

Example:

1. In project 1, search for "status:open".
2. In project 2, search for "status:closed".
3. Navigate to Bigboard.
4. Search for "status:open assignee:me" on the Bigboard page.
5. Navigate back to project 1 and 2 - their searches are now "status:open assignee:me".

What I'm expecting is that the Bigboard search would be separate from the per-project searches.  I added a new session variable, `bigboardSearch`, and use that instead of the per-project searches.  The pull request addresses my use case and expectations, but I could see that other people might have different ideas on how this should work.

**Comment by BlueTeck** [comment]
Thanks for your PR
