### ISSUE TITLE
Schema queries don't work for Postgresql

### ISSUE THREAD

**Issue by johnwoltman** [BlueTeck/kanboard_plugin_bigboard#2]
I got this error on a fresh install of Bigboard with PostgreSQL 10.
`Unable to migrate schema for the plugin: Bigboard => SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "("`
Which caused the Bigboard plugin to not load.  Fix available in PR #3

**Comment by BlueTeck** [comment]
Fixed

**Comment by BlueTeck** [comment]
Sorry for my late answer, didn't saw this issue.

**Comment by johnwoltman** [comment]
@BlueTeck No worries :D
