### ISSUE TITLE
[feature request] Add a Link in bigboard for root Kanboard url and activitiy stream

### ISSUE THREAD

**Issue by Jieiku** [BlueTeck/kanboard_plugin_bigboard#26]
I normally visit my KanBoard install by using a bookmark that takes me straight to the BigBoard.

The problem is the activity stream and new project buttons only exist on the base Kanboard URL, so you need two bookmarks.

I am proposing that a link to the base KanBoard URL be added to the bigboard, it would also be nice if we had a link to view the activity stream or create a new project directly from the BigBoard.

BigBoard Links:

![2021-12-01_18-19](https://user-images.githubusercontent.com/106644/144345554-131990d8-8aff-43db-8075-7baa07371439.png)

New Links Added:

![2021-12-01_18-27](https://user-images.githubusercontent.com/106644/144346290-10bfa98e-de19-4777-804f-2a8301e72fea.png)

I know you are no longer developing bigboard. I am adding this feature request in the hopes that somebody else see this if they decide to fork and extend the bigboard plugin.

**Comment by xekon** [comment]
well I just figured out you can create a new project from the bigboard page its in the top right corner, somehow I missed this even though we have been using kanboard with bigboard for well over a year.

![2021-12-01_20-14](https://user-images.githubusercontent.com/106644/144356472-d3fdded9-c193-427c-ab07-1485a081db67.png)

**Comment by Jieiku** [comment]
the pull request above #36 takes care of this:

![2021-12-08_22-50](https://user-images.githubusercontent.com/106644/145348004-22e55d90-473c-4d98-9780-b0b413a2dab6.png)

![2021-12-09_03-13](https://user-images.githubusercontent.com/106644/145386254-0fb5b901-9608-4aef-b66e-de79c325fdb9.png)
