### ISSUE TITLE
Move Tasks between Projects

### ISSUE THREAD

**Issue by PapeCoding** [BlueTeck/kanboard_plugin_bigboard#4]
Could you add the possibility to move tasks between projects?

**Comment by PapeCoding** [comment]
If you are interested, I started working on the feature in:
https://github.com/PapeCoding/kanboard_plugin_bigboard

This is not as stable as I hoped it would be. There are sometimes hiccups and sometimes the moving lets tasks vanish

**Comment by BlueTeck** [comment]
Nice idea :)

**Comment by PapeCoding** [comment]
I did fix some bugs in the plugin and am quite sure now, that it works. Can you test it and integrate the changes?

**Comment by BlueTeck** [comment]
Very nice, thanks. Changes are merged into master. I will make a new release soon.
