### ISSUE TITLE
Closed projects can't be removed from Bigboard

### ISSUE THREAD

**Issue by johnwoltman** [BlueTeck/kanboard_plugin_bigboard#7]
When a project is closed, it is no longer shown on Bigboard's "Project Selection" list, and it can't be unchecked.

Possible solutions:

1. Automatically remove "closed" projects from the BigBoard.  This is what I kind of expected when closing a project, but maybe some people still want closed projects to show up until they manually remove the project.

2. Show closed projects on the Project Selection list.  Might make sense from a UI perspective, but I don't know how hard it would be to implement.

![kanboard-bigboard-closed-projects](https://user-images.githubusercontent.com/2498295/78939393-0bc4b780-7a82-11ea-87fe-1ed2602574b3.png)

**Comment by BlueTeck** [comment]
Fixed

All active and all already selected project are displayed now.

**Comment by johnwoltman** [comment]
@BlueTeck thanks for fixing this.  I was trying to fix it myself but I'm still learning Kanboard's database query system and couldn't figure out how to do it.  You rock!

**Comment by BlueTeck** [comment]
Maybe this could help you https://github.com/kanboard/kanboard/blob/master/libs/picodb/README.md

**Comment by johnwoltman** [comment]
Thanks! It's definitely a lot different than what I'm used to (Python/Django).  I hope I can contribute in the future :D
